environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "9"
    - nodejs_version: "8"
    - nodejs_version: "6"
platform:
  - x86
  - x64
matrix:
  fast_finish: true
install:
  - npm install
  - ps: Install-Product node $env:nodejs_version
test_script:
  - node --version
  - npm --version
  - npm test
build: off